'use strict';
// ── Official Riot subclass taxonomy ─────────────────────────────────────────
// Sources: Riot Games champion class documentation + LoL Wiki
// Keys match Data Dragon champion IDs exactly.

const CHAMPION_CLASSES = {
  // ── VANGUARDS – engage/offensive tanks ──────────────────────────────────
  Alistar:      { sub: 'Vanguard',    primary: 'Tank' },
  Amumu:        { sub: 'Vanguard',    primary: 'Tank' },
  Galio:        { sub: 'Vanguard',    primary: 'Tank' },
  Gnar:         { sub: 'Vanguard',    primary: 'Tank' },
  Gragas:       { sub: 'Vanguard',    primary: 'Tank' },
  JarvanIV:     { sub: 'Vanguard',    primary: 'Tank' },
  Kennen:       { sub: 'Vanguard',    primary: 'Tank' },
  Leona:        { sub: 'Vanguard',    primary: 'Tank' },
  Malphite:     { sub: 'Vanguard',    primary: 'Tank' },
  Maokai:       { sub: 'Vanguard',    primary: 'Tank' },
  Nautilus:     { sub: 'Vanguard',    primary: 'Tank' },
  Nunu:         { sub: 'Vanguard',    primary: 'Tank' },
  Ornn:         { sub: 'Vanguard',    primary: 'Tank' },
  Rammus:       { sub: 'Vanguard',    primary: 'Tank' },
  Rell:         { sub: 'Vanguard',    primary: 'Tank' },
  Sejuani:      { sub: 'Vanguard',    primary: 'Tank' },
  Sion:         { sub: 'Vanguard',    primary: 'Tank' },
  Zac:          { sub: 'Vanguard',    primary: 'Tank' },
  Rakan:        { sub: 'Vanguard',    primary: 'Support' },
  Wukong:       { sub: 'Vanguard',    primary: 'Fighter' },  // MonkeyKing
  KSante:       { sub: 'Vanguard',    primary: 'Tank' },

  // ── WARDENS – protective/peel tanks ─────────────────────────────────────
  Braum:        { sub: 'Warden',      primary: 'Tank' },
  Poppy:        { sub: 'Warden',      primary: 'Tank' },
  TahmKench:    { sub: 'Warden',      primary: 'Tank' },
  Taric:        { sub: 'Warden',      primary: 'Support' },
  Trundle:      { sub: 'Warden',      primary: 'Fighter' },
  Shen:         { sub: 'Warden',      primary: 'Tank' },

  // ── JUGGERNAUTS – damage + tanky, low mobility ───────────────────────────
  Aatrox:       { sub: 'Juggernaut',  primary: 'Fighter' },
  Ambessa:      { sub: 'Juggernaut',  primary: 'Fighter' },
  Briar:        { sub: 'Juggernaut',  primary: 'Fighter' },
  Chogath:      { sub: 'Juggernaut',  primary: 'Tank' },
  Darius:       { sub: 'Juggernaut',  primary: 'Fighter' },
  DrMundo:      { sub: 'Juggernaut',  primary: 'Tank' },
  Garen:        { sub: 'Juggernaut',  primary: 'Fighter' },
  Illaoi:       { sub: 'Juggernaut',  primary: 'Fighter' },
  Mordekaiser:  { sub: 'Juggernaut',  primary: 'Fighter' },
  Nasus:        { sub: 'Juggernaut',  primary: 'Fighter' },
  Olaf:         { sub: 'Juggernaut',  primary: 'Fighter' },
  Sett:         { sub: 'Juggernaut',  primary: 'Fighter' },
  Shyvana:      { sub: 'Juggernaut',  primary: 'Fighter' },
  Udyr:         { sub: 'Juggernaut',  primary: 'Fighter' },
  Urgot:        { sub: 'Juggernaut',  primary: 'Fighter' },
  Vladimir:     { sub: 'Juggernaut',  primary: 'Mage' },    // some classify as Battle Mage, but plays like Juggernaut
  Volibear:     { sub: 'Juggernaut',  primary: 'Fighter' },
  Warwick:      { sub: 'Juggernaut',  primary: 'Fighter' },

  // ── DIVERS – mobile fighters diving the backline ─────────────────────────
  Camille:      { sub: 'Diver',       primary: 'Fighter' },
  Diana:        { sub: 'Diver',       primary: 'Fighter' },
  Elise:        { sub: 'Diver',       primary: 'Mage' },
  Hecarim:      { sub: 'Diver',       primary: 'Fighter' },
  Irelia:       { sub: 'Diver',       primary: 'Fighter' },
  Kayn:         { sub: 'Diver',       primary: 'Fighter' },
  Kled:         { sub: 'Diver',       primary: 'Fighter' },
  LeeSin:       { sub: 'Diver',       primary: 'Fighter' },
  Nocturne:     { sub: 'Diver',       primary: 'Fighter' },
  Pantheon:     { sub: 'Diver',       primary: 'Fighter' },
  RekSai:       { sub: 'Diver',       primary: 'Fighter' },
  Renekton:     { sub: 'Diver',       primary: 'Fighter' },
  Vi:           { sub: 'Diver',       primary: 'Fighter' },
  XinZhao:      { sub: 'Diver',       primary: 'Fighter' },
  Yone:         { sub: 'Diver',       primary: 'Fighter' },

  // ── ASSASSINS – burst, pick off squishies ────────────────────────────────
  Akali:        { sub: 'Assassin',    primary: 'Assassin' },
  Ekko:         { sub: 'Assassin',    primary: 'Assassin' },
  Evelynn:      { sub: 'Assassin',    primary: 'Assassin' },
  Fizz:         { sub: 'Assassin',    primary: 'Assassin' },
  Kassadin:     { sub: 'Assassin',    primary: 'Mage' },
  Katarina:     { sub: 'Assassin',    primary: 'Assassin' },
  Khazix:       { sub: 'Assassin',    primary: 'Assassin' },
  Leblanc:      { sub: 'Assassin',    primary: 'Mage' },
  Naafiri:      { sub: 'Assassin',    primary: 'Assassin' },
  Nidalee:      { sub: 'Assassin',    primary: 'Mage' },
  Pyke:         { sub: 'Assassin',    primary: 'Support' },
  Qiyana:       { sub: 'Assassin',    primary: 'Assassin' },
  Rengar:       { sub: 'Assassin',    primary: 'Assassin' },
  Shaco:        { sub: 'Assassin',    primary: 'Assassin' },
  Talon:        { sub: 'Assassin',    primary: 'Assassin' },
  Zed:          { sub: 'Assassin',    primary: 'Assassin' },

  // ── SKIRMISHERS – sustained duelists ─────────────────────────────────────
  Akshan:       { sub: 'Skirmisher',  primary: 'Marksman' },
  Aurora:       { sub: 'Skirmisher',  primary: 'Fighter' },
  BelVeth:      { sub: 'Skirmisher',  primary: 'Fighter' },
  Belveth:      { sub: 'Skirmisher',  primary: 'Fighter' },
  Fiora:        { sub: 'Skirmisher',  primary: 'Fighter' },
  Gwen:         { sub: 'Skirmisher',  primary: 'Fighter' },
  Jax:          { sub: 'Skirmisher',  primary: 'Fighter' },
  MasterYi:     { sub: 'Skirmisher',  primary: 'Assassin' },
  Nilah:        { sub: 'Skirmisher',  primary: 'Fighter' },
  Riven:        { sub: 'Skirmisher',  primary: 'Fighter' },
  Sylas:        { sub: 'Skirmisher',  primary: 'Mage' },
  Tryndamere:   { sub: 'Skirmisher',  primary: 'Fighter' },
  Vayne:        { sub: 'Skirmisher',  primary: 'Marksman' },
  Viego:        { sub: 'Skirmisher',  primary: 'Fighter' },
  Yasuo:        { sub: 'Skirmisher',  primary: 'Fighter' },

  // ── BURST MAGES – single-target or burst AoE ────────────────────────────
  Ahri:         { sub: 'Burst Mage',  primary: 'Mage' },
  Annie:        { sub: 'Burst Mage',  primary: 'Mage' },
  Brand:        { sub: 'Burst Mage',  primary: 'Mage' },
  Fiddlesticks: { sub: 'Burst Mage',  primary: 'Mage' },
  Hwei:         { sub: 'Burst Mage',  primary: 'Mage' },
  Lissandra:    { sub: 'Burst Mage',  primary: 'Mage' },
  Lux:          { sub: 'Burst Mage',  primary: 'Mage' },
  Mel:          { sub: 'Burst Mage',  primary: 'Mage' },
  Neeko:        { sub: 'Burst Mage',  primary: 'Mage' },
  Orianna:      { sub: 'Burst Mage',  primary: 'Mage' },
  Seraphine:    { sub: 'Burst Mage',  primary: 'Support' },
  Syndra:       { sub: 'Burst Mage',  primary: 'Mage' },
  TwistedFate:  { sub: 'Burst Mage',  primary: 'Mage' },
  Veigar:       { sub: 'Burst Mage',  primary: 'Mage' },
  Vex:          { sub: 'Burst Mage',  primary: 'Mage' },
  Viktor:       { sub: 'Burst Mage',  primary: 'Mage' },
  Zoe:          { sub: 'Burst Mage',  primary: 'Mage' },

  // ── BATTLE MAGES – sustained AoE/frontline mages ────────────────────────
  Anivia:       { sub: 'Battle Mage', primary: 'Mage' },
  AurelionSol:  { sub: 'Battle Mage', primary: 'Mage' },
  Cassiopeia:   { sub: 'Battle Mage', primary: 'Mage' },
  Karthus:      { sub: 'Battle Mage', primary: 'Mage' },
  Rumble:       { sub: 'Battle Mage', primary: 'Fighter' },
  Ryze:         { sub: 'Battle Mage', primary: 'Mage' },
  Swain:        { sub: 'Battle Mage', primary: 'Mage' },

  // ── ARTILLERY MAGES – extreme range glass cannons ───────────────────────
  Azir:         { sub: 'Artillery',   primary: 'Mage' },
  Corki:        { sub: 'Artillery',   primary: 'Marksman' },
  Ezreal:       { sub: 'Artillery',   primary: 'Marksman' },
  Jayce:        { sub: 'Artillery',   primary: 'Fighter' },
  Smolder:      { sub: 'Artillery',   primary: 'Marksman' },
  Taliyah:      { sub: 'Artillery',   primary: 'Mage' },
  VelKoz:       { sub: 'Artillery',   primary: 'Mage' },
  Velkoz:       { sub: 'Artillery',   primary: 'Mage' },
  Xerath:       { sub: 'Artillery',   primary: 'Mage' },
  Ziggs:        { sub: 'Artillery',   primary: 'Mage' },

  // ── ENCHANTERS – heal, shield, buff supports ─────────────────────────────
  Ivern:        { sub: 'Enchanter',   primary: 'Support' },
  Janna:        { sub: 'Enchanter',   primary: 'Support' },
  Karma:        { sub: 'Enchanter',   primary: 'Support' },
  Lulu:         { sub: 'Enchanter',   primary: 'Support' },
  Milio:        { sub: 'Enchanter',   primary: 'Support' },
  Nami:         { sub: 'Enchanter',   primary: 'Support' },
  Renata:       { sub: 'Enchanter',   primary: 'Support' },
  Sona:         { sub: 'Enchanter',   primary: 'Support' },
  Soraka:       { sub: 'Enchanter',   primary: 'Support' },
  Yuumi:        { sub: 'Enchanter',   primary: 'Support' },
  Zilean:       { sub: 'Enchanter',   primary: 'Support' },

  // ── CATCHERS – CC / lockdown supports ───────────────────────────────────
  Bard:         { sub: 'Catcher',     primary: 'Support' },
  Blitzcrank:   { sub: 'Catcher',     primary: 'Tank' },
  Lillia:       { sub: 'Catcher',     primary: 'Mage' },
  Malzahar:     { sub: 'Catcher',     primary: 'Mage' },
  Morgana:      { sub: 'Catcher',     primary: 'Support' },
  Skarner:      { sub: 'Catcher',     primary: 'Tank' },
  Thresh:       { sub: 'Catcher',     primary: 'Support' },
  Varus:        { sub: 'Catcher',     primary: 'Marksman' },
  Zyra:         { sub: 'Catcher',     primary: 'Support' },

  // ── MARKSMEN – ranged physical carries ───────────────────────────────────
  Aphelios:     { sub: 'Marksman',    primary: 'Marksman' },
  Ashe:         { sub: 'Marksman',    primary: 'Marksman' },
  Caitlyn:      { sub: 'Marksman',    primary: 'Marksman' },
  Draven:       { sub: 'Marksman',    primary: 'Marksman' },
  Graves:       { sub: 'Marksman',    primary: 'Marksman' },
  Jhin:         { sub: 'Marksman',    primary: 'Marksman' },
  Jinx:         { sub: 'Marksman',    primary: 'Marksman' },
  Kaisa:        { sub: 'Marksman',    primary: 'Marksman' },
  Kalista:      { sub: 'Marksman',    primary: 'Marksman' },
  Kindred:      { sub: 'Marksman',    primary: 'Marksman' },
  KogMaw:       { sub: 'Marksman',    primary: 'Marksman' },
  Lucian:       { sub: 'Marksman',    primary: 'Marksman' },
  MissFortune:  { sub: 'Marksman',    primary: 'Marksman' },
  Quinn:        { sub: 'Marksman',    primary: 'Marksman' },
  Samira:       { sub: 'Marksman',    primary: 'Marksman' },
  Senna:        { sub: 'Marksman',    primary: 'Support' },
  Sivir:        { sub: 'Marksman',    primary: 'Marksman' },
  Tristana:     { sub: 'Marksman',    primary: 'Marksman' },
  Twitch:       { sub: 'Marksman',    primary: 'Marksman' },
  Xayah:        { sub: 'Marksman',    primary: 'Marksman' },
  Zeri:         { sub: 'Marksman',    primary: 'Marksman' },

  // ── SPECIALISTS – resist classification ─────────────────────────────────
  Gangplank:    { sub: 'Specialist',  primary: 'Fighter' },
  Heimerdinger: { sub: 'Specialist',  primary: 'Mage' },
  Kayle:        { sub: 'Specialist',  primary: 'Fighter' },
  Singed:       { sub: 'Specialist',  primary: 'Tank' },
  Teemo:        { sub: 'Specialist',  primary: 'Assassin' },
  Yorick:       { sub: 'Specialist',  primary: 'Fighter' },

  // ── NEW (2025–2026) ──────────────────────────────────────────────────────
  Yunara:       { sub: 'Marksman',    primary: 'Marksman' }, // ADC – "the Unbroken Faith"
  Zaahen:       { sub: 'Skirmisher',  primary: 'Fighter' },  // Fighter/Assassin – "The Unsundered"
};

// ── Aliases – maps normalised user input → Data Dragon ID ────────────────────
// Normalisation: name.toLowerCase().replace(/[^a-z]/g, '')
const ALIASES = {
  // ── Champion name variants ────────────────────────────────────────────────
  'wukong':             'MonkeyKing',
  'monkeyking':         'MonkeyKing',
  'nunuandwillump':     'Nunu',
  'nunuwillump':        'Nunu',
  'renataglasc':        'Renata',
  'belveth':            'Belveth',

  // ── Common abbreviations (especially from your Excel) ────────────────────
  'malz':               'Malzahar',
  'liss':               'Lissandra',
  'morg':               'Morgana',
  'malph':              'Malphite',
  'lilia':              'Lillia',
  'morde':              'Mordekaiser',
  'mao':                'Maokai',
  'noc':                'Nocturne',
  'kart':               'Karthus',
  'mundo':              'DrMundo',
  'blitz':              'Blitzcrank',
  'tahm':               'TahmKench',
  'naut':               'Nautilus',
  'vlad':               'Vladimir',
  'j4':                 'JarvanIV',
  'jarvan':             'JarvanIV',
  'tf':                 'TwistedFate',
  'mf':                 'MissFortune',
  'yi':                 'MasterYi',
  'asol':               'AurelionSol',
  'aurelian':           'AurelionSol',
  'aurelianssol':       'AurelionSol',
  'aurelians':          'AurelionSol',
  'xin':                'XinZhao',
  'cho':                'Chogath',
  'lesin':              'LeeSin',
  'lee':                'LeeSin',
  'ksante':             'KSante',
  'graves':             'Graves',
  'vel':                'Velkoz',
  'velcoz':             'Velkoz',
  'zed':                'Zed',
  'yune':               'Yunara',
};

// ── Subclass visual config ────────────────────────────────────────────────────
const CLASS_CONFIG = {
  'Vanguard':    { color: '#4a9ede', bg: '#0d2033', label: 'Vanguard',    group: 'Tank' },
  'Warden':      { color: '#2980b9', bg: '#0a1a27', label: 'Warden',      group: 'Tank' },
  'Juggernaut':  { color: '#e05c2a', bg: '#2a1008', label: 'Juggernaut',  group: 'Fighter' },
  'Diver':       { color: '#e67e22', bg: '#2a1800', label: 'Diver',       group: 'Fighter' },
  'Assassin':    { color: '#c0392b', bg: '#250808', label: 'Assassin',    group: 'Slayer' },
  'Skirmisher':  { color: '#e74c3c', bg: '#2a0a0a', label: 'Skirmisher',  group: 'Slayer' },
  'Burst Mage':  { color: '#9b59d6', bg: '#1a0a2a', label: 'Burst Mage', group: 'Mage' },
  'Battle Mage': { color: '#8e44ad', bg: '#160820', label: 'Battle Mage', group: 'Mage' },
  'Artillery':   { color: '#6c3483', bg: '#120618', label: 'Artillery',   group: 'Mage' },
  'Enchanter':   { color: '#f1c40f', bg: '#292200', label: 'Enchanter',   group: 'Support' },
  'Catcher':     { color: '#f39c12', bg: '#231900', label: 'Catcher',     group: 'Support' },
  'Marksman':    { color: '#27ae60', bg: '#051a0c', label: 'Marksman',    group: 'Marksman' },
  'Specialist':  { color: '#7f8c8d', bg: '#141a1a', label: 'Specialist',  group: 'Specialist' },
};

// ── Champion comp-traits ──────────────────────────────────────────────────────
// What each champion actually DOES in a comp, independent of their subclass.
// Vocabulary: poke, siege, engage, disengage, peel, pick, splitpush, dive,
//             aoe, burst, earlygame, scaling, hypercarry, sustain, kite
// Champions without an entry fall back to subclass-only scoring.
const CHAMP_TRAITS = {
  Aatrox:       ['sustain', 'aoe', 'dive'],
  Ahri:         ['pick', 'burst', 'kite'],
  Akali:        ['burst', 'dive', 'pick'],
  Alistar:      ['engage', 'peel', 'dive'],
  Ambessa:      ['dive', 'pick', 'earlygame', 'splitpush'],
  Amumu:        ['engage', 'aoe'],
  Anivia:       ['aoe', 'disengage', 'scaling', 'peel'],
  Annie:        ['burst', 'aoe', 'engage'],
  Aphelios:     ['scaling', 'hypercarry'],
  Ashe:         ['pick', 'kite', 'poke'],
  AurelionSol:  ['scaling', 'aoe'],
  Aurora:       ['burst', 'kite', 'pick'],
  Azir:         ['poke', 'disengage', 'scaling', 'siege'],
  Bard:         ['pick', 'disengage', 'peel'],
  Belveth:      ['scaling', 'splitpush', 'dive'],
  Blitzcrank:   ['pick', 'engage', 'peel'],
  Brand:        ['aoe', 'burst', 'poke'],
  Braum:        ['peel', 'disengage'],
  Briar:        ['dive', 'earlygame', 'sustain'],
  Caitlyn:      ['poke', 'siege', 'earlygame', 'kite'],
  Camille:      ['splitpush', 'dive', 'pick', 'engage'],
  Cassiopeia:   ['scaling', 'kite', 'aoe', 'sustain'],
  Chogath:      ['scaling', 'aoe'],
  Corki:        ['poke', 'siege', 'scaling'],
  Darius:       ['earlygame', 'sustain'],
  Diana:        ['aoe', 'dive', 'burst', 'engage'],
  DrMundo:      ['sustain', 'scaling', 'splitpush'],
  Draven:       ['earlygame', 'hypercarry'],
  Ekko:         ['burst', 'dive', 'pick'],
  Elise:        ['pick', 'dive', 'earlygame', 'burst'],
  Evelynn:      ['pick', 'burst'],
  Ezreal:       ['poke', 'kite', 'siege'],
  Fiddlesticks: ['aoe', 'engage', 'burst'],
  Fiora:        ['splitpush', 'sustain'],
  Fizz:         ['burst', 'dive', 'pick'],
  Galio:        ['engage', 'aoe', 'peel'],
  Gangplank:    ['splitpush', 'scaling', 'aoe'],
  Garen:        ['sustain', 'splitpush'],
  Gnar:         ['engage', 'aoe', 'kite'],
  Gragas:       ['engage', 'disengage', 'aoe', 'pick'],
  Graves:       ['earlygame', 'burst'],
  Gwen:         ['splitpush', 'scaling', 'sustain'],
  Hecarim:      ['engage', 'dive', 'aoe'],
  Heimerdinger: ['siege', 'poke'],
  Hwei:         ['poke', 'aoe', 'siege', 'disengage'],
  Illaoi:       ['splitpush', 'sustain', 'aoe'],
  Irelia:       ['dive', 'splitpush'],
  Ivern:        ['peel', 'disengage', 'sustain'],
  Janna:        ['disengage', 'peel', 'kite'],
  JarvanIV:     ['engage', 'aoe', 'earlygame', 'dive'],
  Jax:          ['splitpush', 'scaling', 'dive'],
  Jayce:        ['poke', 'siege', 'earlygame'],
  Jhin:         ['pick', 'poke'],
  Jinx:         ['scaling', 'hypercarry', 'siege'],
  KSante:       ['engage', 'pick', 'peel'],
  Kaisa:        ['dive', 'scaling', 'hypercarry', 'burst'],
  Kalista:      ['earlygame', 'kite', 'engage'],
  Karma:        ['poke', 'peel', 'disengage', 'kite'],
  Karthus:      ['scaling', 'aoe'],
  Kassadin:     ['scaling', 'burst'],
  Katarina:     ['burst', 'aoe'],
  Kayle:        ['scaling', 'hypercarry', 'peel'],
  Kayn:         ['dive', 'pick'],
  Kennen:       ['engage', 'aoe'],
  Khazix:       ['pick', 'burst', 'earlygame', 'dive'],
  Kindred:      ['kite', 'scaling'],
  Kled:         ['engage', 'dive', 'earlygame'],
  KogMaw:       ['hypercarry', 'scaling', 'siege'],
  Leblanc:      ['burst', 'pick'],
  LeeSin:       ['earlygame', 'dive', 'pick'],
  Leona:        ['engage', 'pick', 'aoe', 'earlygame'],
  Lillia:       ['aoe', 'kite', 'scaling'],
  Lissandra:    ['engage', 'aoe', 'pick', 'burst'],
  Lucian:       ['earlygame', 'burst'],
  Lulu:         ['peel', 'sustain', 'disengage'],
  Lux:          ['poke', 'pick', 'burst', 'siege'],
  Malphite:     ['engage', 'aoe'],
  Malzahar:     ['pick'],
  Maokai:       ['engage', 'aoe', 'peel'],
  MasterYi:     ['scaling', 'hypercarry'],
  Mel:          ['burst', 'poke', 'scaling'],
  Milio:        ['peel', 'sustain', 'disengage', 'kite'],
  MissFortune:  ['aoe', 'burst'],
  MonkeyKing:   ['engage', 'aoe', 'dive'],
  Mordekaiser:  ['splitpush', 'pick', 'sustain'],
  Morgana:      ['pick', 'peel'],
  Naafiri:      ['pick', 'burst', 'dive'],
  Nami:         ['sustain', 'peel', 'disengage'],
  Nasus:        ['scaling', 'splitpush', 'sustain'],
  Nautilus:     ['engage', 'pick', 'peel'],
  Neeko:        ['aoe', 'pick', 'engage'],
  Nidalee:      ['poke', 'earlygame', 'pick'],
  Nilah:        ['aoe', 'scaling'],
  Nocturne:     ['dive', 'pick'],
  Nunu:         ['engage', 'aoe'],
  Olaf:         ['earlygame', 'dive', 'sustain'],
  Orianna:      ['aoe', 'peel', 'scaling'],
  Ornn:         ['engage', 'aoe', 'scaling', 'peel'],
  Pantheon:     ['earlygame', 'dive', 'pick', 'burst'],
  Poppy:        ['peel', 'disengage'],
  Pyke:         ['pick', 'engage', 'burst'],
  Qiyana:       ['burst', 'pick', 'aoe'],
  Quinn:        ['splitpush'],
  Rakan:        ['engage', 'aoe', 'peel', 'disengage'],
  Rammus:       ['engage'],
  RekSai:       ['pick', 'dive', 'earlygame'],
  Rell:         ['engage', 'aoe', 'peel'],
  Renata:       ['peel', 'disengage', 'aoe'],
  Renekton:     ['earlygame', 'dive'],
  Rengar:       ['pick', 'burst', 'dive'],
  Riven:        ['earlygame', 'burst'],
  Rumble:       ['aoe'],
  Ryze:         ['scaling', 'splitpush'],
  Samira:       ['aoe', 'dive', 'earlygame'],
  Sejuani:      ['engage', 'aoe', 'peel'],
  Senna:        ['poke', 'scaling', 'sustain'],
  Seraphine:    ['aoe', 'disengage', 'sustain', 'peel'],
  Sett:         ['engage', 'earlygame'],
  Shaco:        ['pick', 'splitpush'],
  Shen:         ['peel', 'splitpush'],
  Shyvana:      ['scaling', 'aoe'],
  Singed:       ['splitpush', 'sustain'],
  Sion:         ['engage', 'aoe', 'splitpush', 'scaling'],
  Sivir:        ['kite', 'aoe', 'siege'],
  Skarner:      ['engage', 'pick', 'peel', 'aoe'],
  Smolder:      ['scaling', 'kite'],
  Sona:         ['sustain', 'aoe', 'scaling', 'peel'],
  Soraka:       ['sustain', 'peel'],
  Swain:        ['aoe', 'sustain', 'pick'],
  Sylas:        ['burst', 'dive', 'sustain'],
  Syndra:       ['burst', 'pick', 'scaling'],
  TahmKench:    ['peel', 'disengage', 'sustain'],
  Taliyah:      ['poke', 'aoe', 'disengage', 'pick'],
  Talon:        ['burst', 'pick', 'earlygame'],
  Taric:        ['peel', 'sustain'],
  Teemo:        ['poke', 'splitpush', 'kite'],
  Thresh:       ['pick', 'engage', 'peel'],
  Tristana:     ['siege', 'scaling'],
  Trundle:      ['splitpush', 'disengage', 'sustain'],
  Tryndamere:   ['splitpush'],
  TwistedFate:  ['pick', 'splitpush'],
  Twitch:       ['hypercarry', 'scaling', 'pick', 'aoe'],
  Udyr:         ['splitpush', 'sustain'],
  Urgot:        ['pick', 'splitpush'],
  Varus:        ['poke', 'siege', 'pick'],
  Vayne:        ['hypercarry', 'scaling', 'kite'],
  Veigar:       ['scaling', 'burst', 'pick'],
  Velkoz:       ['poke', 'aoe', 'siege'],
  Vex:          ['burst', 'pick'],
  Vi:           ['dive', 'pick', 'engage'],
  Viego:        ['pick', 'dive', 'burst'],
  Viktor:       ['aoe', 'siege', 'scaling', 'poke'],
  Vladimir:     ['scaling', 'sustain', 'aoe'],
  Volibear:     ['dive', 'engage', 'sustain'],
  Warwick:      ['dive', 'pick', 'sustain'],
  Xayah:        ['kite', 'scaling', 'disengage'],
  Xerath:       ['poke', 'siege', 'aoe'],
  XinZhao:      ['earlygame', 'dive'],
  Yasuo:        ['dive', 'scaling'],
  Yone:         ['dive', 'splitpush', 'scaling'],
  Yorick:       ['splitpush', 'siege'],
  Yuumi:        ['sustain', 'peel', 'scaling'],
  Yunara:       ['hypercarry', 'scaling'],
  Zaahen:       ['splitpush', 'dive'],   // new 2026 champ – rough estimate
  Zac:          ['engage', 'aoe', 'sustain'],
  Zed:          ['pick', 'burst', 'splitpush'],
  Zeri:         ['kite', 'scaling', 'hypercarry'],
  Ziggs:        ['poke', 'siege', 'aoe'],
  Zilean:       ['peel', 'disengage'],
  Zoe:          ['poke', 'pick', 'burst'],
  Zyra:         ['poke', 'aoe', 'pick'],
};

// ── Per-template trait weighting ──────────────────────────────────────────────
// core = defines the comp (+7 each), good = supports the plan (+2 each),
// bad = actively against the plan (−5 each). Applied on top of subclass fit.
const TEMPLATE_TRAITS = {
  hard_engage:     { core: ['engage'],             good: ['aoe', 'pick', 'dive', 'peel'],                  bad: ['poke'] },
  poke:            { core: ['poke'],               good: ['siege', 'kite', 'disengage', 'pick'],           bad: ['engage', 'dive'] },
  protect_carry:   { core: ['peel'],               good: ['sustain', 'disengage', 'scaling', 'hypercarry'], bad: ['dive'] },
  pick:            { core: ['pick'],               good: ['burst', 'dive', 'engage'],                      bad: [] },
  split_push:      { core: ['splitpush'],          good: ['pick', 'scaling', 'disengage'],                 bad: [] },
  teamfight_aoe:   { core: ['aoe'],                good: ['engage', 'peel', 'scaling'],                    bad: ['splitpush'] },
  early_snowball:  { core: ['earlygame'],          good: ['dive', 'pick', 'burst', 'engage'],              bad: ['scaling'] },
  kite_disengage:  { core: ['kite', 'disengage'],  good: ['peel', 'poke', 'scaling'],                      bad: ['dive'] },
  siege:           { core: ['siege'],              good: ['poke', 'disengage', 'peel', 'kite'],            bad: ['dive'] },
  dive:            { core: ['dive'],               good: ['engage', 'burst', 'earlygame', 'pick'],         bad: ['poke'] },
  enchanter_scale: { core: ['sustain'],            good: ['peel', 'scaling', 'hypercarry', 'disengage'],   bad: ['earlygame'] },
  burst_assassin:  { core: ['burst'],              good: ['pick', 'dive', 'earlygame'],                    bad: [] },
};

// ── Meta Comp Templates ───────────────────────────────────────────────────────
// roles[slot] = ordered array of preferred subclasses (index 0 = ideal)
const COMP_TEMPLATES = [
  {
    id: 'hard_engage',
    name: 'Hard Engage',
    emoji: '💥',
    color: '#e05c2a',
    description: 'Lock the enemy down with hard CC chains and win through superior teamfighting.',
    winCondition: 'Group up, find a 5v5 engage, chain AoE CC for easy kills',
    strengths: ['Teamfighting', 'Objective control', 'Scales into mid game'],
    weaknesses: ['Poke heavy comps', 'Kite-back comps', 'Split push pressure'],
    roles: {
      top:     ['Vanguard', 'Juggernaut', 'Warden'],
      jungle:  ['Vanguard', 'Diver', 'Juggernaut'],
      mid:     ['Burst Mage', 'Vanguard', 'Battle Mage'],
      bot:     ['Marksman', 'Catcher'],
      support: ['Vanguard', 'Catcher', 'Enchanter'],
    },
    keyChamps: ['Malphite', 'Amumu', 'Orianna', 'Leona', 'Nautilus'],
  },
  {
    id: 'poke',
    name: 'Poke',
    emoji: '🏹',
    color: '#27ae60',
    description: 'Whittle enemies from safety. Force bad engages or take objectives at low HP.',
    winCondition: 'Reduce enemies to 50% HP, deny healing, siege objectives',
    strengths: ['Safe', 'Objective pressure', 'Hard to all-in'],
    weaknesses: ['All-in comps', 'Heavy sustain', 'Split push'],
    roles: {
      top:     ['Artillery', 'Specialist', 'Juggernaut'],
      jungle:  ['Artillery', 'Diver', 'Skirmisher'],
      mid:     ['Artillery', 'Burst Mage', 'Battle Mage'],
      bot:     ['Marksman', 'Artillery'],
      support: ['Enchanter', 'Catcher', 'Artillery'],
    },
    keyChamps: ['Jayce', 'Nidalee', 'Zoe', 'Ezreal', 'Karma'],
  },
  {
    id: 'protect_carry',
    name: 'Protect the Carry',
    emoji: '🛡',
    color: '#f1c40f',
    description: 'Shield, heal, and peel for your hypercarry. Let them scale and 1v5.',
    winCondition: 'Survive to late game; once the ADC has 3 items, nothing can kill them',
    strengths: ['Late game', 'Consistent damage', 'Hard to burst down'],
    weaknesses: ['Early game', 'Assassin dive', 'Hard engage before items'],
    roles: {
      top:     ['Warden', 'Juggernaut', 'Enchanter'],
      jungle:  ['Enchanter', 'Warden', 'Diver'],
      mid:     ['Enchanter', 'Burst Mage', 'Battle Mage'],
      bot:     ['Marksman'],
      support: ['Enchanter', 'Warden'],
    },
    keyChamps: ['Lulu', 'Soraka', 'Yuumi', 'Kog\'Maw', 'Jinx'],
  },
  {
    id: 'pick',
    name: 'Pick Comp',
    emoji: '🎯',
    color: '#9b59d6',
    description: 'Catch out isolated enemies to create numbers advantages before objectives.',
    winCondition: 'Pick off lone targets, take objectives with the man advantage',
    strengths: ['Map control', 'Punishes poor positioning', 'Objective focused'],
    weaknesses: ['Grouped teams', 'Peel comps', 'Hard engage responds fast'],
    roles: {
      top:     ['Diver', 'Assassin', 'Skirmisher'],
      jungle:  ['Assassin', 'Diver', 'Catcher'],
      mid:     ['Catcher', 'Assassin', 'Burst Mage'],
      bot:     ['Marksman', 'Catcher'],
      support: ['Catcher', 'Vanguard'],
    },
    keyChamps: ['Thresh', 'Blitzcrank', 'Ahri', 'Nocturne', 'Lissandra'],
  },
  {
    id: 'split_push',
    name: 'Split Push',
    emoji: '⚔',
    color: '#e74c3c',
    description: '1-3-1 side lane pressure forces enemies to react, creating openings elsewhere.',
    winCondition: 'Force 2 enemies to answer the split; 4v3 wins across the map',
    strengths: ['Map pressure', 'Scales late', 'Hard to teamfight into'],
    weaknesses: ['Can be caught 1v2', 'AoE teamfight comps', 'Poor dragon control'],
    roles: {
      top:     ['Skirmisher', 'Juggernaut', 'Specialist'],
      jungle:  ['Diver', 'Skirmisher', 'Juggernaut'],
      mid:     ['Skirmisher', 'Specialist', 'Burst Mage'],
      bot:     ['Marksman'],
      support: ['Enchanter', 'Catcher'],
    },
    keyChamps: ['Fiora', 'Jax', 'Tryndamere', 'Yorick', 'Camille'],
  },
  {
    id: 'teamfight_aoe',
    name: 'Teamfight / AoE',
    emoji: '💫',
    color: '#3498db',
    description: 'Stack multiple AoE ultimates. Group up and nuke the entire enemy team.',
    winCondition: 'Combo AoE ults simultaneously — Amumu ult + Orianna ball + MF ult',
    strengths: ['Devastating teamfights', 'Dragon/Baron setup', 'Scales well'],
    weaknesses: ['Split push pressure', 'Pick comps', 'Long match-ups'],
    roles: {
      top:     ['Vanguard', 'Juggernaut', 'Battle Mage'],
      jungle:  ['Vanguard', 'Diver', 'Battle Mage'],
      mid:     ['Burst Mage', 'Battle Mage', 'Artillery'],
      bot:     ['Marksman'],
      support: ['Enchanter', 'Vanguard', 'Catcher'],
    },
    keyChamps: ['Amumu', 'Orianna', 'Miss Fortune', 'Jarvan IV', 'Galio'],
  },
  {
    id: 'early_snowball',
    name: 'Early Snowball',
    emoji: '❄',
    color: '#00bcd4',
    description: 'Dominate early and end before the enemy scales. Win by 25 minutes.',
    winCondition: 'Win early fights, take first tower, snowball pressure into objectives',
    strengths: ['Punishes weak early laners', 'Snowballing', 'Short games'],
    weaknesses: ['Scaling comps', 'Stall tactics', 'Healing sustain'],
    roles: {
      top:     ['Diver', 'Juggernaut', 'Skirmisher'],
      jungle:  ['Diver', 'Assassin', 'Vanguard'],
      mid:     ['Assassin', 'Burst Mage', 'Diver'],
      bot:     ['Marksman'],
      support: ['Vanguard', 'Catcher'],
    },
    keyChamps: ['Renekton', 'Lee Sin', 'Zed', 'Draven', 'Leona'],
  },
  {
    id: 'kite_disengage',
    name: 'Kite & Disengage',
    emoji: '🌀',
    color: '#1abc9c',
    description: 'Create distance, punish overaggression. Reposition while dealing consistent damage.',
    winCondition: 'Force the enemy into bad angles; punish overextensions with ranged damage',
    strengths: ['Safe', 'Punishes dive comps', 'Consistent late game'],
    weaknesses: ['Hard engage', 'Heavy AoE', 'Siege'],
    roles: {
      top:     ['Warden', 'Marksman', 'Specialist'],
      jungle:  ['Diver', 'Skirmisher', 'Enchanter'],
      mid:     ['Artillery', 'Burst Mage', 'Catcher'],
      bot:     ['Marksman'],
      support: ['Enchanter', 'Catcher', 'Warden'],
    },
    keyChamps: ['Vayne', 'Ashe', 'Caitlyn', 'Janna', 'Poppy'],
  },
  {
    id: 'siege',
    name: 'Siege',
    emoji: '🏰',
    color: '#e67e22',
    description: 'Outrange towers and poke enemies off them. Win through sustained structure damage.',
    winCondition: 'Zone enemies off turrets, poke them out, slowly take structures',
    strengths: ['Safe structure damage', 'Objective focused', 'Hard to engage on'],
    weaknesses: ['All-in burst', 'Hard engage', 'Mobile flankers'],
    roles: {
      top:     ['Artillery', 'Specialist', 'Juggernaut'],
      jungle:  ['Vanguard', 'Diver'],
      mid:     ['Artillery', 'Burst Mage', 'Specialist'],
      bot:     ['Marksman', 'Artillery'],
      support: ['Enchanter', 'Catcher', 'Artillery'],
    },
    keyChamps: ['Ziggs', 'Xerath', 'Jayce', 'Caitlyn', 'Heimerdinger'],
  },
  {
    id: 'dive',
    name: 'All-in Dive',
    emoji: '🦅',
    color: '#c0392b',
    description: 'Multiple divers and assassins simultaneously jump the backline.',
    winCondition: 'Dive from 3+ angles at once; eliminate carries before they react',
    strengths: ['Instantly kills carries', 'Snowball potential', 'Overwhelming pressure'],
    weaknesses: ['Peel-heavy comps', 'Warden tanks', 'AoE CC punishes grouping'],
    roles: {
      top:     ['Diver', 'Assassin', 'Juggernaut'],
      jungle:  ['Diver', 'Assassin'],
      mid:     ['Assassin', 'Diver', 'Burst Mage'],
      bot:     ['Marksman', 'Skirmisher'],
      support: ['Vanguard', 'Catcher'],
    },
    keyChamps: ['Camille', 'Lee Sin', 'Zed', 'Kaisa', 'Nautilus'],
  },
  {
    id: 'enchanter_scale',
    name: 'Enchanter / Scale',
    emoji: '✨',
    color: '#ff6b9d',
    description: 'Stack heals and shields. Become nearly unkillable in the late game.',
    winCondition: 'Reach late game; multiple enchanter items make your carries immortal',
    strengths: ['Extreme late game', 'Sustain in long fights', 'Safe scaling'],
    weaknesses: ['Anti-heal items', 'Hard engage early', 'Poor early-mid transitions'],
    roles: {
      top:     ['Juggernaut', 'Warden', 'Enchanter'],
      jungle:  ['Enchanter', 'Diver', 'Warden'],
      mid:     ['Enchanter', 'Burst Mage', 'Battle Mage'],
      bot:     ['Marksman'],
      support: ['Enchanter'],
    },
    keyChamps: ['Soraka', 'Lulu', 'Yuumi', 'Sona', 'Kog\'Maw'],
  },
  {
    id: 'burst_assassin',
    name: 'Burst / Assassin',
    emoji: '⚡',
    color: '#8e44ad',
    description: 'Delete high-priority targets in under a second. Win through mechanical outplays.',
    winCondition: 'Find picks in fog of war; assassinate carries before anyone can react',
    strengths: ['1v1 dominance', 'Punishes isolation', 'Snowball comps'],
    weaknesses: ['Tanky frontlines', 'Warden supports', 'Grouped enemies with peel'],
    roles: {
      top:     ['Assassin', 'Skirmisher', 'Diver'],
      jungle:  ['Assassin', 'Diver'],
      mid:     ['Assassin', 'Burst Mage'],
      bot:     ['Marksman', 'Skirmisher'],
      support: ['Catcher', 'Assassin'],
    },
    keyChamps: ['Zed', 'Katarina', 'Akali', 'Kaisa', 'Pyke'],
  },
];
